### ISSUE TITLE
Empty Available Devices

### ISSUE THREAD

**Issue by pfeodoo2021** [h4nyu/react-native-zebra#7]
Hi 

When I use the package in my react-native I get an empty list when I call Rfid.GetAvailableDevices() 
But when when I use another app it works and read rfid tags 

NB : my device is TC20 with RFD2000

**Comment by h4nyu** [comment]
I only tested with RFD8500 and I don't have RFD2000 device.

`Rfid.GetAvailableDevices` is equivalent to GetAvailableRFIDReaderList in java.

You can try download Zebra_RFIDAPI3_SDK_2.0.1.34.zip from [ZEBRA RFID READER SDK FOR ANDROID](https://www.zebra.com/us/en/support-downloads/software/developer-tools/rfid-sdk-for-android.html) and check to see if `SDKSample` working or not.

**Comment by pfeodoo2021** [comment]
Hi @h4nyu

I did as you said and it works 
<img width="375" alt="TC20" src="https://user-images.githubusercontent.com/83483676/123614938-b7c7ff00-d7fc-11eb-89e2-96a8f0606e06.PNG">

My code is below
<img width="697" alt="RN_RFID_CODE" src="https://user-images.githubusercontent.com/83483676/123615052-d6c69100-d7fc-11eb-9088-3e94043171e3.PNG">

 And the result is 
<img width="676" alt="RN_LOG" src="https://user-images.githubusercontent.com/83483676/123615096-e34ae980-d7fc-11eb-8f6b-f43df2aa113b.PNG">

If I have something wrong in my code pleaese tell where is it

Thank you

**Comment by pfeodoo2021** [comment]
Any ideas why it's not working
